server:
  port: 80

eureka:
  instance:
    hostname: 10.178.0.3
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://10.178.0.3:8761/eureka

spring:
  application:
    name: gateway
