# Generated by Django 4.2.7 on 2023-11-12 06:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem_id", models.IntegerField()),
                ("user_id", models.IntegerField()),
                ("is_passed", models.BooleanField(default=False)),
                ("is_judged", models.BooleanField(default=False)),
                ("judge_status", models.IntegerField(default=301)),
                ("source", models.TextField(default="")),
                ("language_code", models.IntegerField(default=0)),
                (
                    "created_time",
                    models.DateTimeField(default=django.utils.timezone.localtime),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
            ],
        ),
    ]
