# Generated by Django 4.2.7 on 2023-11-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sub", "0002_alter_submission_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="error_message",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="judge_description",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="judge_status",
            field=models.IntegerField(default=0),
        ),
    ]
