# Generated by Django 4.2.7 on 2023-12-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sub", "0003_submission_error_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="memory_used",
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="time_used",
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
