# Parameters
SOURCE="source"
LANGUAGE="language"
USER_ID="user_id"
PROBLEM_ID="problem_id"

# Language Codes
LANGUAGE_DEFAULT=0
LANGUAGE_C=1
LANGUAGE_JAVA=2
LANGUAGE_PYTHON=3

# SOURCE CODE
SOURCE_DEFAULT=""

# JUDGE STATUS
JUDGE_SUCCESS=200
JUDGE_CREATED=301
JUDGE_PENDING=302
JUDGE_RUNNING=303
JUDGE_FAILURE=400
JUDGE_ERROR_COMPILE=500
JUDGE_ERROR_RUNTIME=500